project_id = "obirpzwvnqveddyuulsb"

[functions.send-reapplication-notifications]
verify_jwt = false

[functions.send-ban-appeal-notification]
verify_jwt = true

[functions.fetch-discord-user]
verify_jwt = true

[functions.send-gallery-notification]
verify_jwt = false

[functions.check-sla-notifications]
verify_jwt = false

[functions.auto-assign-chats]
verify_jwt = false

[functions.send-owner-message]
verify_jwt = true

[functions.send-refund-notification]
verify_jwt = true

[functions.send-promo-code-email]
verify_jwt = true
