project_id = "obirpzwvnqveddyuulsb"

[functions.send-reapplication-notifications]
verify_jwt = false

[functions.send-ban-appeal-notification]
verify_jwt = true

[functions.fetch-discord-user]
verify_jwt = false

[functions.send-gallery-notification]
verify_jwt = false

[functions.check-sla-notifications]
verify_jwt = false

[functions.auto-assign-chats]
verify_jwt = false

[functions.send-owner-message]
verify_jwt = true

[functions.send-refund-notification]
verify_jwt = true

[functions.send-promo-code-email]
verify_jwt = true

[functions.notify-unauthorized-owner-access]
verify_jwt = true

[functions.send-feedback-notification]
verify_jwt = true

[functions.verify-discord-requirements]
verify_jwt = true

[functions.sync-discord-presence]
verify_jwt = false

[functions.send-creator-notification]
verify_jwt = true

[functions.sync-staff-discord-info]
verify_jwt = false

[functions.sync-discord-events]
verify_jwt = false

[functions.verify-roster-permissions]
verify_jwt = false

[functions.verify-discord-membership]
verify_jwt = false

[functions.send-giveaway-notification]
verify_jwt = false
