project_id = "obirpzwvnqveddyuulsb"

[functions.send-reapplication-notifications]
verify_jwt = false

[functions.send-ban-appeal-notification]
verify_jwt = false

[functions.fetch-discord-user]
verify_jwt = false

[functions.send-gallery-notification]
verify_jwt = false

[functions.check-sla-notifications]
verify_jwt = false
